# Generated by Django 3.2.23 on 2026-09-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionModels',
            fields=[
                ('auction_id', models.IntegerField(primary_key=True, serialize=False)),
                ('group_id', models.IntegerField(default=0)),
                ('month_index', models.IntegerField(default=1)),
                ('label', models.CharField(blank=True, default='', max_length=60)),
                ('status', models.CharField(blank=True, default='Upcoming', max_length=30)),
                ('scheduled_date', models.CharField(blank=True, default='', max_length=30)),
                ('start_time', models.CharField(blank=True, default='', max_length=20)),
                ('end_time', models.CharField(blank=True, default='', max_length=20)),
                ('starting_bid', models.FloatField(default=0)),
                ('bid_increment', models.FloatField(default=0)),
                ('winner_member_id', models.IntegerField(blank=True, default=None, null=True)),
                ('winning_bid', models.FloatField(blank=True, default=None, null=True)),
                ('prize_amount', models.FloatField(blank=True, default=None, null=True)),
                ('commission', models.FloatField(blank=True, default=None, null=True)),
                ('dividend_per_member', models.FloatField(blank=True, default=None, null=True)),
                ('final_installment', models.FloatField(blank=True, default=None, null=True)),
                ('confirmed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'auction_table',
            },
        ),
        migrations.CreateModel(
            name='BidModels',
            fields=[
                ('bid_id', models.IntegerField(primary_key=True, serialize=False)),
                ('auction_id', models.IntegerField(default=0)),
                ('member_id', models.IntegerField(default=0)),
                ('member_name', models.CharField(blank=True, default='', max_length=150)),
                ('amount', models.FloatField(default=0)),
                ('time', models.CharField(blank=True, default='', max_length=30)),
            ],
            options={
                'db_table': 'bid_table',
            },
        ),
        migrations.CreateModel(
            name='ChitGroupModels',
            fields=[
                ('group_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('chit_value', models.FloatField(default=0)),
                ('total_members', models.IntegerField(default=0)),
                ('duration_months', models.IntegerField(default=0)),
                ('monthly_installment', models.FloatField(default=0)),
                ('auction_day', models.IntegerField(default=1)),
                ('start_date', models.CharField(blank=True, default='', max_length=30)),
                ('status', models.CharField(blank=True, default='Upcoming', max_length=20)),
                ('current_month', models.IntegerField(default=0)),
                ('starting_bid', models.FloatField(default=0)),
                ('min_bid', models.FloatField(default=0)),
                ('max_bid', models.FloatField(default=0)),
                ('bid_increment', models.FloatField(default=0)),
                ('commission_type', models.CharField(blank=True, default='Fixed', max_length=20)),
                ('commission_value', models.FloatField(default=0)),
                ('foreman', models.CharField(blank=True, default='', max_length=150)),
                ('admin_id', models.IntegerField(default=0)),
                ('created_date', models.CharField(blank=True, default='', max_length=30)),
            ],
            options={
                'db_table': 'group_table',
            },
        ),
        migrations.CreateModel(
            name='DividendModels',
            fields=[
                ('dividend_id', models.IntegerField(primary_key=True, serialize=False)),
                ('group_id', models.IntegerField(default=0)),
                ('month_index', models.IntegerField(default=0)),
                ('auction_id', models.IntegerField(default=0)),
                ('per_member', models.FloatField(default=0)),
                ('total_pool', models.FloatField(default=0)),
                ('eligible_members', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'dividend_table',
            },
        ),
        migrations.CreateModel(
            name='MemberModels',
            fields=[
                ('member_id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='', max_length=30)),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.CharField(blank=True, default='', max_length=250)),
                ('nominee', models.CharField(blank=True, default='', max_length=150)),
                ('bank_account', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(blank=True, default='Active', max_length=20)),
                ('join_date', models.CharField(blank=True, default='', max_length=30)),
                ('admin_id', models.IntegerField(default=0)),
                ('created_date', models.CharField(blank=True, default='', max_length=30)),
            ],
            options={
                'db_table': 'member_table',
            },
        ),
        migrations.CreateModel(
            name='MembershipModels',
            fields=[
                ('membership_id', models.IntegerField(primary_key=True, serialize=False)),
                ('group_id', models.IntegerField(default=0)),
                ('member_id', models.IntegerField(default=0)),
                ('chit_number', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'membership_table',
            },
        ),
        migrations.CreateModel(
            name='NotificationModels',
            fields=[
                ('notification_id', models.IntegerField(primary_key=True, serialize=False)),
                ('audience', models.CharField(blank=True, default='admin', max_length=20)),
                ('member_id', models.IntegerField(blank=True, default=None, null=True)),
                ('group_id', models.IntegerField(blank=True, default=None, null=True)),
                ('admin_id', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('message', models.CharField(blank=True, default='', max_length=400)),
                ('type', models.CharField(blank=True, default='system', max_length=20)),
                ('time', models.CharField(blank=True, default='', max_length=30)),
                ('read', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'notification_table',
            },
        ),
        migrations.CreateModel(
            name='PaymentModels',
            fields=[
                ('payment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('group_id', models.IntegerField(default=0)),
                ('member_id', models.IntegerField(default=0)),
                ('month_index', models.IntegerField(default=0)),
                ('type', models.CharField(blank=True, default='Installment', max_length=20)),
                ('amount', models.FloatField(default=0)),
                ('due_date', models.CharField(blank=True, default='', max_length=30)),
                ('paid_date', models.CharField(blank=True, default='', max_length=30)),
                ('status', models.CharField(blank=True, default='Pending', max_length=20)),
                ('method', models.CharField(blank=True, default='', max_length=30)),
                ('transaction_id', models.CharField(blank=True, default='', max_length=60)),
            ],
            options={
                'db_table': 'payment_table',
            },
        ),
        migrations.CreateModel(
            name='UserModels',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('role', models.CharField(blank=True, default='member', max_length=20)),
                ('password', models.CharField(blank=True, default='', max_length=100)),
                ('org_name', models.CharField(blank=True, default='', max_length=150)),
                ('member_id', models.IntegerField(blank=True, default=None, null=True)),
                ('admin_id', models.IntegerField(blank=True, default=None, null=True)),
                ('created_date', models.CharField(blank=True, default='', max_length=30)),
            ],
            options={
                'db_table': 'user_table',
            },
        ),
    ]
